using System.Text;

namespace SoftThorn.SourceGenerators
{
    public static class SourceGenerationHelper
    {
        public const string Header = """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            """;

        public const string Attribute = Header + """
                                        namespace SoftThorn.SourceGenerators
                                        {
                                            [AttributeUsage(AttributeTargets.Enum, AllowMultiple = false)]
                                            public sealed class GenerateDtoAttribute : Attribute;
                                        }
                                        """;


        public const string Dto = Header + """
                                  namespace SoftThorn.SourceGenerators
                                  {
                                      public readonly record struct EnumDto
                                      {
                                          required public int Id { get; init; }

                                          required public string DisplayName { get; init; }

                                          required public int Order { get; init; }
                                      }
                                  }
                                  """;

        public const string BaseInterface = Header +  """
                                            namespace SoftThorn.SourceGenerators
                                            {
                                                public interface IEnumService
                                                {
                                                    IEnumerable<EnumDto> GetDtos();
                                                }
                                            }
                                            """;

        public const string GenericInterface = Header + """
                                               namespace SoftThorn.SourceGenerators
                                               {
                                                   public interface IEnumService<TEnum> : IEnumService;
                                               }
                                               """;

        public static string GenerateEnumServiceClass(List<EnumToGenerate> enumsToGenerate)
        {
            var sb = new StringBuilder();

            sb.Append(Header + @"
namespace SoftThorn.SourceGenerators
{");
            foreach (var enumToGenerate in enumsToGenerate)
            {
                sb.Append(@"
    public sealed class ").Append(enumToGenerate.Name).Append(@"EnumService : IEnumService<").Append(enumToGenerate.FullName).Append(@">
    {").Append(@"
        public IEnumerable<EnumDto> GetDtos()
        {");
                if (enumToGenerate.Values.Count == 0)
                {
                    sb.Append(@"
            yield break;
");
                }
                else
                {
                    foreach (var member in enumToGenerate.Values)
                    {
                        sb.Append(@"
            yield return new EnumDto()
            {
                Id = (int)").Append(enumToGenerate.FullName).Append('.').Append(member.Value).Append(@",
                DisplayName = ").Append(member.DisplayName).Append(',').Append(@"
                Order = ").Append(member.Order).Append(',').Append(@"
            };").AppendLine();
                    }
                }
                sb.Append(@"        }
    }
");
            }

            sb.Append(@"
}");
            return sb.ToString();
        }
    }
}
